### ISSUE TITLE
data为null,导制出错，重启二十多次。

### ISSUE THREAD

**Issue by hezedu** [node-webot/wechat-api#20]
/usr/local/software/node/nodeWechat/node_modules/wechat-api/lib/util.js:12
    if (data.errcode) {
            ^
TypeError: Cannot read property 'errcode' of null
    at /usr/local/software/node/nodeWechat/node_modules/wechat-api/lib/util.js:12:13
    at done (/usr/local/software/node/nodeWechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:346:5)
    at /usr/local/software/node/nodeWechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:547:9
    at decodeContent (/usr/local/software/node/nodeWechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:407:14)
    at IncomingMessage.<anonymous> (/usr/local/software/node/nodeWechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:513:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #24

**Comment by JacksonTian** [comment]
升级到最新的版本。
