### ISSUE TITLE
模板消息发送不成功，代码有未定义的变量导致报错

### ISSUE THREAD

**Issue by TooBug** [node-webot/wechat-api#238]
https://github.com/node-webot/wechat-api/blob/master/lib/api_template.js#L210

看这行代码，`url`变量未定义，导致报错。应该是重构了函数签名导致的吧，原来的函数签名中`url`是一个形参。

```
/www/node_modules/wechat-api/lib/api_template.js:210
    url = dest;
        ^

ReferenceError: url is not defined
    at API.exports._sendTemplate (/www/node_modules/wechat-api/lib/api_template.js:210:9)
    at /www/node_modules/wechat-api/lib/api_common.js:240:16
    at /www/node_modules/wechat-api/lib/api_common.js:185:7
    at API.saveToken (/www/node_modules/wechat-api/lib/api_common.js:77:5)
    at /www/node_modules/wechat-api/lib/api_common.js:181:10
    at /www/node_modules/wechat-api/lib/util.js:26:5
    at done (/www/node_modules/urllib/lib/urllib.js:441:5)
    at /www/node_modules/urllib/lib/urllib.js:676:9
    at decodeContent (/www/node_modules/urllib/lib/urllib.js:514:14)
    at IncomingMessage.<anonymous> (/www/node_modules/urllib/lib/urllib.js:641:7)
```

**Comment by JacksonTian** [comment]
来个 PR 吧。

**Comment by highmore** [comment]
api_template.js:210 里面的 url 和 miniprogram 2个局部变量未定义，自己先声明一下就可以用了。等待下个升级修正。

**Comment by jerrwy** [comment]
+1

**Comment by flight9** [comment]
作者已经修复了 截止on 2/27, 2018
