### ISSUE TITLE
发送模板消息一直提示change template too frequently hint

### ISSUE THREAD

**Issue by sivanzheng** [node-webot/wechat-api#242]
WeChatAPIError: change template too frequently hint: [3cVEWa0775vr19]
  at E:\wechat\server\node_modules\wechat-api\lib\util.js:15:13
  at done (E:\wechat\server\node_modules\urllib\lib\urllib.js:441:5)
  at E:\wechat\server\node_modules\urllib\lib\urllib.js:676:9
  at decodeContent (E:\wechat\server\node_modules\urllib\lib\urllib.js:514:14)
  at IncomingMessage.<anonymous> (E:\wechat\server\node_modules\urllib\lib\urllib.js:641:7)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9) name: 'WeChatAPIError', code: 43100

在微信公众号开发文档的返回码中并没有43100

**Comment by JacksonTian** [comment]
消息已经说得很明白了啊。太频繁了

**Comment by sivanzheng** [comment]
@JacksonTian  问题是我只使用了一个模板 并没有改变模板 也没换过模板id

**Comment by anxiaowen2** [comment]
不太懂什么意思，那发送模板消息的限制是多少呢？

**Comment by JacksonTian** [comment]
参见官方文档。

**Comment by DiligentWangTwo** [comment]
change template too frequently 不仅是频繁请求会报，如果模板消息在模板库里不存在了也会报
