### ISSUE TITLE
Error code: 48001, message: api unauthorized 

### ISSUE THREAD

**Issue by STANAPI** [node-webot/wechat-api#253]
请问以下是什么问题？我该如何解决？

“Error code: 48001, message: api unauthorized”

若还需要什么详情资料，请通知我。谢谢！

**Comment by STANAPI** [comment]
The WeChat API Call encountered the following exception: 
Traceback (most recent call last):
  File "C:\STB\STAN_MG_API\WeChat\wc_follower_total.py", line 30, in extract
    data = client.user.get_followers()
  File "C:\STB\STAN_MG_API\WeChat\wechatpy\client\api\user.py", line 60, in get_followers
    params=params
  File "C:\STB\STAN_MG_API\WeChat\wechatpy\client\api\base.py", line 13, in _get
    return self._client.get(url, **kwargs)
  File "C:\STB\STAN_MG_API\WeChat\wechatpy\client\base.py", line 182, in get
    **kwargs
  File "C:\STB\STAN_MG_API\WeChat\wechatpy\client\base.py", line 115, in _request
    res, method, url, result_processor, **kwargs
  File "C:\STB\STAN_MG_API\WeChat\wechatpy\client\base.py", line 173, in _handle_result
    response=res
wechatpy.exceptions.WeChatClientException: Error code: 48001, message: api unauthorized hint: [FNYrYa0206k455!]

**Comment by JacksonTian** [comment]
The repo just used for Node.js users.
