### ISSUE TITLE
上传多媒体的接口貌似不通了， 望你们测试一下

### ISSUE THREAD

**Issue by RajanZhan** [node-webot/wechat-api#255]
uploadVoice。
会报这个错误，是不是微信的接口改了，我自己写的接口也会报这个错，望你们修复，不然这个模块不完整了。

 { WeChatAPIError: system error hint: [YlPkia03201464]
    at C:\Project\wxApi\APIforDoctorWorkstation\node_modules\wechat-api\lib\util
.js:15:13
    at done (C:\Project\wxApi\APIforDoctorWorkstation\node_modules\wechat-api\no
de_modules\urllib\lib\urllib.js:441:5)
    at C:\Project\wxApi\APIforDoctorWorkstation\node_modules\wechat-api\node_mod
ules\urllib\lib\urllib.js:676:9
    at decodeContent (C:\Project\wxApi\APIforDoctorWorkstation\node_modules\wech
at-api\node_modules\urllib\lib\urllib.js:514:14)
    at IncomingMessage.<anonymous> (C:\Project\wxApi\APIforDoctorWorkstation\nod
e_modules\wechat-api\node_modules\urllib\lib\urllib.js:641:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) name: 'WeChat
APIError', code: -1 } { errcode: -1, errmsg: 'system error hint: [YlPkia03201464
]' }

**Comment by JacksonTian** [comment]
系统错误 应该是后端的问题了。
