### ISSUE TITLE
看日志发现一个崩溃的情况

### ISSUE THREAD

**Issue by TooBug** [node-webot/wechat-api#26]
```
source/node_modules/wechat/node_modules/wechat-api/lib/util.js:12
    if (data.errcode) {
            ^
TypeError: Cannot read property 'errcode' of null
    at source/node_modules/wechat/node_modules/wechat-api/lib/util.js:12:13
    at done (source/node_modules/wechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:346:5)
    at source/node_modules/wechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:547:9
    at decodeContent (source/node_modules/wechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:407:14)
    at IncomingMessage.<anonymous> (source/node_modules/wechat/node_modules/wechat-api/node_modules/urllib/lib/urllib.js:513:7)
    at IncomingMessage.emit (events.js:119:20)
    at _stream_readable.js:888:16
    at process._tickCallback (node.js:337:11)
```

对应的是util.js中第12行

```javascript
exports.wrapper = function (callback) {
  return function (err, data, res) {
    callback = callback || function () {};
    if (err) {
      err.name = 'WeChatAPI' + err.name;
      return callback(err, data, res);
    }
    if (data.errcode) { //这一行，data为空进崩溃
      err = new Error(data.errmsg);
      err.name = 'WeChatAPIError';
      err.code = data.errcode;
      return callback(err, data, res);
    }
    callback(null, data, res);
  };
};
```

追查到urllib.js的547行调用，再之前是对`data`的处理，不知是否有极端情况没考虑到。

```javascript
      decodeContent(res, body, function (err, data, encoding) {
        if (err) {
          return done(err, body, res);
        }
        // if body not decode, dont touch it
        if (!encoding && TEXT_DATA_TYPES.indexOf(args.dataType) >= 0) {
          // try to decode charset
          try {
            data = decodeBodyByCharset(data, res);
          } catch (_) {
            // if error, dont touch it
            return done(null, data, res);
          }

          if (args.dataType === 'json') {
            if (responseSize === 0) {
              data = null;
            } else {
              var r = parseJSON(data);
              if (r.error) {
                err = r.error;
              } else {
                data = r.data;
              }
            }
          }
        }

        if (responseAborted) {
          // err = new Error('Remote socket was terminated before `response.end()` was called');
          // err.name = 'RemoteSocketClosedError';
          debug('Request#%d %s: Remote socket was terminated before `response.end()` was called', reqId, url);
        }

        done(err, data, res); //547行，data为空
      });
```

**Comment by JacksonTian** [comment]
使用wechat-api的时候，请单独引入吧：`require('wechat-api');` wechat里的是比较旧的版本了。
